trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildAndPublishMain
  displayName: 'Build and Publish Main Package'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      version: 9.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions

  - script: dotnet --version

  - task: DotNetCoreCLI@2
    displayName: 'Restore Main'
    inputs:
      command: 'restore'
      projects: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Build Main $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.csproj'
      arguments: '-c $(buildConfiguration)'
      # configuration: '$(buildConfiguration)'
      versioningScheme: 'off'
  - task: DotNetCoreCLI@2
    displayName: 'Pack Main'
    inputs:
      command: 'pack'
      packagesToPack: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.csproj'
      configuration: '$(buildConfiguration)'
      nobuild: true
      versioningScheme: 'off'
  - task: NuGetCommand@2
    displayName: 'Push Main Package to Feed'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/Mscc.GenerativeAI.*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(publishVstsFeed)'
      allowPackageConflicts: true

- job: BuildAndPublishDependents
  displayName: 'Build and Publish Dependent Packages'
  dependsOn: BuildAndPublishMain
  condition: succeeded()
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      version: 9.x
  - task: DotNetCoreCLI@2
    displayName: 'Restore packages'
    inputs:
      command: 'restore'
      projects: './GenerativeAI.sln'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: 'Build Solution $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: './GenerativeAI.sln'
      arguments: '-c $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: 'Pack for ASP.NET Core'
    inputs:
      command: 'pack'
      packagesToPack: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.Web.csproj'
      nobuild: true
      versioningScheme: 'off'
  - task: DotNetCoreCLI@2
    displayName: 'Pack for .NET using Google Cloud Client Library'
    inputs:
      command: 'pack'
      packagesToPack: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.Google.csproj'
      nobuild: true
      versioningScheme: 'off'
  - task: DotNetCoreCLI@2
    displayName: 'Pack for Microsoft.Extension.AI and Microsoft Semantic Kernel'
    inputs:
      command: 'pack'
      packagesToPack: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.Microsoft.csproj'
      nobuild: true
      versioningScheme: 'off'
  - task: NuGetCommand@2
    displayName: 'Push Dependent Packages to Feed'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg;!$(Build.ArtifactStagingDirectory)/Mscc.GenerativeAI.*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(publishVstsFeed)'
      allowPackageConflicts: true